# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [1]:
import pandas as pd
df = pd.read_csv("dataset.csv",sep = "|",header = None)
df.columns = ["user_id", "age", "gender", "occupation", "zip_code"]

In [2]:
df.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [3]:
df.tail(5)

     user_id  age gender     occupation zip_code
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    str
 3   occupation  943 non-null    str
 4   zip_code    943 non-null    str
dtypes: int64(2), str(3)
memory usage: 37.0 KB

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [12]:
df_2 = pd.read_csv("dataset_2.csv")
df_2.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [11]:
df_2_index = df_2.set_index("country")
df_2_index

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [16]:
df_2_index.loc["Zimbabwe"]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [17]:
df_2_index.loc["Zimbabwe", "continent"]

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [36]:
df_3 = pd.read_csv("dataset_3.csv")
df_3.isnull().sum()
df_3.columns = df_3.columns.str.lower().str.replace(" ", "_")
df_3 = df_3.drop_duplicates()
colonnes = ["city", "colors_reported", "shape_reported"]
df_3[colonnes] = df_3[colonnes].fillna("Unknown")
df_3["time"] = pd.to_datetime(df_3["time"], format="%m/%d/%Y %H:%M")
df_3.info()

<class 'pandas.DataFrame'>
Index: 18132 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   city             18132 non-null  str
 1   colors_reported  18132 non-null  str
 2   shape_reported   18132 non-null  str
 3   state            18132 non-null  str
 4   time             18132 non-null  datetime64[us]
dtypes: datetime64[us](1), str(4)
memory usage: 849.9 KB

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [38]:
df_3.iloc[:3, :]

          city colors_reported shape_reported state                time
0       Ithaca         Unknown       TRIANGLE    NY 1930-06-01 22:00:00
1  Willingboro         Unknown          OTHER    NJ 1930-06-30 20:00:00
2      Holyoke         Unknown           OVAL    CO 1931-02-15 14:00:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [40]:
df_3.loc[0:2, :]

          city colors_reported shape_reported state                time
0       Ithaca         Unknown       TRIANGLE    NY 1930-06-01 22:00:00
1  Willingboro         Unknown          OTHER    NJ 1930-06-30 20:00:00
2      Holyoke         Unknown           OVAL    CO 1931-02-15 14:00:00